"""Explicit operation manifest shared by CLI and MCP surfaces."""

from meridian.lib.extensions.types import ExtensionCommandSpec, ExtensionSurface
from meridian.lib.ops.catalog import (
    ModelsListInput,
    ModelsListOutput,
    models_list,
    models_list_sync,
)
from meridian.lib.ops.config import (
    ConfigGetInput,
    ConfigGetOutput,
    ConfigInitInput,
    ConfigInitOutput,
    ConfigResetInput,
    ConfigResetOutput,
    ConfigSetInput,
    ConfigSetOutput,
    ConfigShowInput,
    ConfigShowOutput,
    config_get,
    config_get_sync,
    config_init,
    config_init_sync,
    config_reset,
    config_reset_sync,
    config_set,
    config_set_sync,
    config_show,
    config_show_sync,
)
from meridian.lib.ops.context import (
    ContextInput,
    ContextOutput,
    WorkCurrentInput,
    WorkCurrentOutput,
    WorkRootInput,
    WorkRootOutput,
    context,
    context_sync,
    work_current,
    work_current_sync,
    work_root,
    work_root_sync,
)
from meridian.lib.ops.diag import DoctorInput, DoctorOutput, doctor, doctor_sync
from meridian.lib.ops.hooks import (
    HookCheckInput,
    HookCheckOutput,
    HookListInput,
    HookListOutput,
    HookResolveInput,
    HookResolveOutput,
    HookRunInput,
    HookRunOutput,
    hooks_check,
    hooks_check_sync,
    hooks_list,
    hooks_list_sync,
    hooks_resolve,
    hooks_resolve_sync,
    hooks_run,
    hooks_run_sync,
)
from meridian.lib.ops.report import (
    ReportSearchInput,
    ReportSearchOutput,
    ReportShowInput,
    ReportShowOutput,
    report_search,
    report_search_sync,
    report_show,
    report_show_sync,
)
from meridian.lib.ops.session_export import (
    SessionExportInput,
    SessionExportOutput,
    session_export,
    session_export_sync,
)
from meridian.lib.ops.session_log import (
    SessionLogInput,
    SessionLogOutput,
    session_log,
    session_log_sync,
)
from meridian.lib.ops.session_search import (
    SessionSearchInput,
    SessionSearchOutput,
    session_search,
    session_search_sync,
)
from meridian.lib.ops.spawn.api import (
    SpawnActionOutput,
    SpawnCancelAllInput,
    SpawnCancelAllOutput,
    SpawnCancelInput,
    SpawnContinueInput,
    SpawnCreateInput,
    SpawnDetailOutput,
    SpawnListInput,
    SpawnListOutput,
    SpawnShowInput,
    SpawnStatsInput,
    SpawnStatsOutput,
    SpawnWaitInput,
    SpawnWaitMultiOutput,
    SpawnWrittenFilesInput,
    SpawnWrittenFilesOutput,
    spawn_cancel,
    spawn_cancel_all,
    spawn_cancel_all_sync,
    spawn_cancel_sync,
    spawn_continue,
    spawn_continue_sync,
    spawn_create,
    spawn_create_sync,
    spawn_files,
    spawn_files_sync,
    spawn_list,
    spawn_list_sync,
    spawn_show,
    spawn_show_sync,
    spawn_stats,
    spawn_stats_sync,
    spawn_wait,
    spawn_wait_sync,
)
from meridian.lib.ops.work_dashboard import (
    WorkListInput,
    WorkListOutput,
    WorkSessionsInput,
    WorkSessionsOutput,
    WorkShowInput,
    WorkShowOutput,
    work_list,
    work_list_sync,
    work_sessions,
    work_sessions_sync,
    work_show,
    work_show_sync,
)
from meridian.lib.ops.work_lifecycle import (
    WorkClearInput,
    WorkClearOutput,
    WorkDeleteInput,
    WorkDeleteOutput,
    WorkDoneInput,
    WorkRenameInput,
    WorkRenameOutput,
    WorkReopenInput,
    WorkReopenOutput,
    WorkStartInput,
    WorkStartOutput,
    WorkSwitchInput,
    WorkSwitchOutput,
    WorkUpdateInput,
    WorkUpdateOutput,
    work_clear,
    work_clear_sync,
    work_delete,
    work_delete_sync,
    work_done,
    work_done_sync,
    work_rename,
    work_rename_sync,
    work_reopen,
    work_reopen_sync,
    work_start,
    work_start_sync,
    work_switch,
    work_switch_sync,
    work_update,
    work_update_sync,
)
from meridian.lib.ops.workspace import (
    WorkspaceInitInput,
    WorkspaceInitOutput,
    WorkspaceMigrateInput,
    WorkspaceMigrateOutput,
    workspace_init,
    workspace_init_sync,
    workspace_migrate,
    workspace_migrate_sync,
)

_OP_SPECS: tuple[ExtensionCommandSpec, ...] = (
    ExtensionCommandSpec.from_op(
        extension_id="meridian.config",
        command_id="get",
        summary="Get one resolved config key with source annotation.",
        handler=config_get,
        sync_handler=config_get_sync,
        input_type=ConfigGetInput,
        output_type=ConfigGetOutput,
        cli_group="config",
        cli_name="get",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.config",
        command_id="init",
        summary="Scaffold meridian.toml with commented defaults.",
        handler=config_init,
        sync_handler=config_init_sync,
        input_type=ConfigInitInput,
        output_type=ConfigInitOutput,
        cli_group="config",
        cli_name="init",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.config",
        command_id="reset",
        summary="Remove one config key from file overrides.",
        handler=config_reset,
        sync_handler=config_reset_sync,
        input_type=ConfigResetInput,
        output_type=ConfigResetOutput,
        cli_group="config",
        cli_name="reset",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.config",
        command_id="set",
        summary="Set one config key in meridian.toml.",
        handler=config_set,
        sync_handler=config_set_sync,
        input_type=ConfigSetInput,
        output_type=ConfigSetOutput,
        cli_group="config",
        cli_name="set",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.config",
        command_id="show",
        summary="Show resolved config values with source annotations.",
        handler=config_show,
        sync_handler=config_show_sync,
        input_type=ConfigShowInput,
        output_type=ConfigShowOutput,
        cli_group="config",
        cli_name="show",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.workspace",
        command_id="init",
        summary="Create local meridian.local.toml workspace scaffold.",
        handler=workspace_init,
        sync_handler=workspace_init_sync,
        input_type=WorkspaceInitInput,
        output_type=WorkspaceInitOutput,
        cli_group="workspace",
        cli_name="init",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.workspace",
        command_id="migrate",
        summary="Migrate legacy workspace.local.toml roots into meridian.local.toml.",
        handler=workspace_migrate,
        sync_handler=workspace_migrate_sync,
        input_type=WorkspaceMigrateInput,
        output_type=WorkspaceMigrateOutput,
        cli_group="workspace",
        cli_name="migrate",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.doctor",
        command_id="doctor",
        summary="Health check and orphan reconciliation.",
        handler=doctor,
        sync_handler=doctor_sync,
        input_type=DoctorInput,
        output_type=DoctorOutput,
        cli_group="doctor",
        cli_name="doctor",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.hooks",
        command_id="check",
        summary="Verify runtime requirements for all built-in hooks.",
        handler=hooks_check,
        sync_handler=hooks_check_sync,
        input_type=HookCheckInput,
        output_type=HookCheckOutput,
        cli_group="hooks",
        cli_name="check",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.hooks",
        command_id="list",
        summary="List registered hooks with event, source, and status.",
        handler=hooks_list,
        sync_handler=hooks_list_sync,
        input_type=HookListInput,
        output_type=HookListOutput,
        cli_group="hooks",
        cli_name="list",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.hooks",
        command_id="resolve",
        summary="Resolve enabled hooks for one event in execution order.",
        handler=hooks_resolve,
        sync_handler=hooks_resolve_sync,
        input_type=HookResolveInput,
        output_type=HookResolveOutput,
        cli_group=None,
        cli_name=None,
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.MCP, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.hooks",
        command_id="run",
        summary="Manually execute one hook by name; bypasses interval throttling.",
        handler=hooks_run,
        sync_handler=hooks_run_sync,
        input_type=HookRunInput,
        output_type=HookRunOutput,
        cli_group="hooks",
        cli_name="run",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.models",
        command_id="list",
        summary="List catalog models with routing guidance.",
        handler=models_list,
        sync_handler=models_list_sync,
        input_type=ModelsListInput,
        output_type=ModelsListOutput,
        cli_group="models",
        cli_name="list",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.report",
        command_id="search",
        summary="Search spawn reports by keyword.",
        handler=report_search,
        sync_handler=report_search_sync,
        input_type=ReportSearchInput,
        output_type=ReportSearchOutput,
        cli_group="report",
        cli_name="search",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.report",
        command_id="show",
        summary="Show one spawn report.",
        handler=report_show,
        sync_handler=report_show_sync,
        input_type=ReportShowInput,
        output_type=ReportShowOutput,
        cli_group="report",
        cli_name="show",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.session",
        command_id="log",
        summary=(
            "Show readable conversation/progress messages for a chat, spawn, "
            "or harness session."
        ),
        handler=session_log,
        sync_handler=session_log_sync,
        input_type=SessionLogInput,
        output_type=SessionLogOutput,
        cli_group="session",
        cli_name="log",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.session",
        command_id="export",
        summary="Export a full session transcript as clean markdown.",
        handler=session_export,
        sync_handler=session_export_sync,
        input_type=SessionExportInput,
        output_type=SessionExportOutput,
        cli_group="session",
        cli_name="export",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.session",
        command_id="search",
        summary="Search a session transcript for case-insensitive text matches.",
        handler=session_search,
        sync_handler=session_search_sync,
        input_type=SessionSearchInput,
        output_type=SessionSearchOutput,
        cli_group="session",
        cli_name="search",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="cancel",
        summary="Cancel a running spawn.",
        handler=spawn_cancel,
        sync_handler=spawn_cancel_sync,
        input_type=SpawnCancelInput,
        output_type=SpawnActionOutput,
        cli_group="spawn",
        cli_name="cancel",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="cancelAll",
        summary="Cancel all running spawns, optionally scoped to one work item.",
        handler=spawn_cancel_all,
        sync_handler=spawn_cancel_all_sync,
        input_type=SpawnCancelAllInput,
        output_type=SpawnCancelAllOutput,
        cli_group="spawn",
        cli_name="cancel-all",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="files",
        summary="List edited files for a spawn, one per line. Pipe to git add or xargs.",
        handler=spawn_files,
        sync_handler=spawn_files_sync,
        input_type=SpawnWrittenFilesInput,
        output_type=SpawnWrittenFilesOutput,
        cli_group="spawn",
        cli_name="files",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="children",
        summary="List child spawns for a parent spawn id.",
        handler=spawn_list,
        sync_handler=spawn_list_sync,
        input_type=SpawnListInput,
        output_type=SpawnListOutput,
        cli_group="spawn",
        cli_name="children",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="continue",
        summary="Continue a previous spawn.",
        handler=spawn_continue,
        sync_handler=spawn_continue_sync,
        input_type=SpawnContinueInput,
        output_type=SpawnActionOutput,
        cli_group="spawn",
        cli_name="continue",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.MCP, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="create",
        summary="Create and start a spawn.",
        handler=spawn_create,
        sync_handler=spawn_create_sync,
        input_type=SpawnCreateInput,
        output_type=SpawnActionOutput,
        cli_group="spawn",
        cli_name="create",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.MCP, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="list",
        summary="List recent spawns (default: active). Filter by --view, --status, or --model.",
        handler=spawn_list,
        sync_handler=spawn_list_sync,
        input_type=SpawnListInput,
        output_type=SpawnListOutput,
        cli_group="spawn",
        cli_name="list",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="show",
        summary=(
            "Show spawn status, duration, model, report path, and report text by default. "
            "Use --no-report to omit report text."
        ),
        handler=spawn_show,
        sync_handler=spawn_show_sync,
        input_type=SpawnShowInput,
        output_type=SpawnDetailOutput,
        cli_group="spawn",
        cli_name="show",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="stats",
        summary="Show total runs, success/fail counts, cost, and duration.",
        handler=spawn_stats,
        sync_handler=spawn_stats_sync,
        input_type=SpawnStatsInput,
        output_type=SpawnStatsOutput,
        cli_group="spawn",
        cli_name="stats",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.spawn",
        command_id="wait",
        summary="Block until spawn(s) complete and return terminal status details.",
        handler=spawn_wait,
        sync_handler=spawn_wait_sync,
        input_type=SpawnWaitInput,
        output_type=SpawnWaitMultiOutput,
        cli_group="spawn",
        cli_name="wait",
        agent_default_format="text",
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="clear",
        summary="Clear the active work item for the current session when available.",
        handler=work_clear,
        sync_handler=work_clear_sync,
        input_type=WorkClearInput,
        output_type=WorkClearOutput,
        cli_group="work",
        cli_name="clear",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="done",
        summary="Mark a work item as done and archive its scratch directory when present.",
        handler=work_done,
        sync_handler=work_done_sync,
        input_type=WorkDoneInput,
        output_type=WorkUpdateOutput,
        cli_group="work",
        cli_name="done",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="delete",
        summary=(
            "Delete a work item. Fails when scratch artifacts exist unless --force is provided."
        ),
        handler=work_delete,
        sync_handler=work_delete_sync,
        input_type=WorkDeleteInput,
        output_type=WorkDeleteOutput,
        cli_group="work",
        cli_name="delete",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="reopen",
        summary=(
            "Reopen a done work item and restore its archived scratch directory when present."
        ),
        handler=work_reopen,
        sync_handler=work_reopen_sync,
        input_type=WorkReopenInput,
        output_type=WorkReopenOutput,
        cli_group="work",
        cli_name="reopen",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="list",
        summary=(
            'List work items. Use --done / --no-done to control whether'
            ' items with status "done" are shown.'
        ),
        handler=work_list,
        sync_handler=work_list_sync,
        input_type=WorkListInput,
        output_type=WorkListOutput,
        cli_group="work",
        cli_name="list",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="rename",
        summary="Rename a work item. Updates the slug, directory, and all spawn associations.",
        handler=work_rename,
        sync_handler=work_rename_sync,
        input_type=WorkRenameInput,
        output_type=WorkRenameOutput,
        cli_group="work",
        cli_name="rename",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="show",
        summary="Show one work item, its directory, and associated spawns.",
        handler=work_show,
        sync_handler=work_show_sync,
        input_type=WorkShowInput,
        output_type=WorkShowOutput,
        cli_group="work",
        cli_name="show",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="sessions",
        summary=(
            "List sessions associated with a work item. "
            "Default shows active sessions; use --all for historical."
        ),
        handler=work_sessions,
        sync_handler=work_sessions_sync,
        input_type=WorkSessionsInput,
        output_type=WorkSessionsOutput,
        cli_group="work",
        cli_name="sessions",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="start",
        summary=(
            "Create a work item if missing, or switch to it if it already exists and is active."
        ),
        handler=work_start,
        sync_handler=work_start_sync,
        input_type=WorkStartInput,
        output_type=WorkStartOutput,
        cli_group="work",
        cli_name="start",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="switch",
        summary="Set the active work item for the current session when available.",
        handler=work_switch,
        sync_handler=work_switch_sync,
        input_type=WorkSwitchInput,
        output_type=WorkSwitchOutput,
        cli_group="work",
        cli_name="switch",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="update",
        summary="Update a work item's status and/or description.",
        handler=work_update,
        sync_handler=work_update_sync,
        input_type=WorkUpdateInput,
        output_type=WorkUpdateOutput,
        cli_group="work",
        cli_name="update",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.context",
        command_id="context",
        summary="Query configured context catalog (work/kb sources and resolved paths).",
        handler=context,
        sync_handler=context_sync,
        input_type=ContextInput,
        output_type=ContextOutput,
        cli_group="context",
        cli_name="context",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="current",
        summary="Return the current work directory path (or empty if none attached).",
        handler=work_current,
        sync_handler=work_current_sync,
        input_type=WorkCurrentInput,
        output_type=WorkCurrentOutput,
        cli_group="work",
        cli_name="current",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
    ExtensionCommandSpec.from_op(
        extension_id="meridian.work",
        command_id="root",
        summary="Return the configured work root directory path.",
        handler=work_root,
        sync_handler=work_root_sync,
        input_type=WorkRootInput,
        output_type=WorkRootOutput,
        cli_group="work",
        cli_name="root",
        agent_default_format="text",
        surfaces=frozenset({ExtensionSurface.CLI, ExtensionSurface.HTTP}),
    ),
)



def get_all_op_specs() -> list[ExtensionCommandSpec]:
    """Return all op-style specs for registration."""

    return list(_OP_SPECS)


__all__ = [
    "get_all_op_specs",
]
